name: "test GHA comments"

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read
  statuses: read
  id-token: write

jobs:
  job_1:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running job_1"
  job_2:
    if: ${{ contains(github.event.comment.body, '.deploy') }}
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running job_2"
