name: "test GHA comments"

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read
  statuses: read
  id-token: write

jobs:
  a_sample_job:
    if: ${{ contains(github.event.comment.body, '.deploy') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Apparently the comment contains the word '.deploy'"
